name: Update Leetcode Status

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 페키지 다운로드
      - run: npm install

      # Runs a single command using the runners shell
      - name: Update
        uses: ./
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GT_TOKEN: ${{ secrets.GT_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
